version: 2.1

build: &build_step
  run:
    name: build project
    command: python3 -m compileall .
#test: &test_step
#  run:
#    name: test project
#    command: python3 python_project/main_test.py

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    working_directory: /python_project/sample1
    steps:
      - checkout
      - *build_step
      - run: ls
      #- store_artifacts:
       #   path: /tmp/
    
workflows:
  pythonbuild:
    jobs:
      - build
  #    - test:
  #        requires:
  #          - build