version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      
      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      
      # Run tests using pytest
      - run:
          name: Run Tests
          command: pytest
      
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
