version: 2.1

build: &build_step
  run:
    name: build project
    command: python3 -m compileall python_project/.
#test: &test_step
#  run:
#    name: test project
#    command: python3 python_project/main_test.py

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    working_directory: /tmp
    steps:
      - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - *build_step
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
      
      - store_artifacts:
          path: --pycache--


workflows:
  pythonbuild:
    jobs:
      - build
  #    - test:
  #        requires:
  #          - build