version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.4

    steps:
      - checkout  # Checkout the source code from your repository

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Compile Python Files to .pyc
          command: python -m compileall .

      # Store the .pyc files as artifacts
      - store_artifacts:
          path: __pycache__  # Replace with the correct path to the __pycache__ directory

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
