version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.4

    steps:
      - checkout  # Checkout the source code from your repository

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Compile Python Files to .pyc
          command: |
            python -m compileall python_project/.;
            mkdir tmp/pycfiles;
          
      - store_artifacts:
          path: python_project/sample1/__pycache__  # Replace with the correct path to the __pycache__ directory
          destination: tmp/pycfiles

      # Store the .pyc files as artifacts
      

workflows:
  build_workflow:
    jobs:
      - build
