version: 2.1

build_step: &build_step
  run: python3 python_project/main.py
test_step: &test_step
  run: python3 python_project/main_test.py

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
    <<: *build_step
      #- run: python3 python_project/main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
    <<: *test_step

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build