version: 2.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - import: build.yml
      #- run: python3 python_project/main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - import: test.yml

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build